### ISSUE TITLE
This seems like the perfect module for model translation... but which version to use on Django 1.7.8?

### ISSUE THREAD

**Issue by gabn88** [specialunderwear/django-easymode#23]
Hi Folks,

What a little gem of a module is this, according to the documentation! It does work exactly how I had my translations in mind, and actually how I started building it. But I found too many traps during programming it myself, so that is why I started looking around if somebody else had done it 'my' way, and I found Django EasyMode!

One question: 
Does it work with Django 1.7.8?
Should I use version 0.14.5 (default from pypi) or another?

**Comment by specialunderwear** [comment]
Should work now.

**Comment by gabn88** [comment]
I'm already using modeltranslations by now, but still thanks for your comment.
